### ISSUE TITLE
Backend HTTP Calls

### ISSUE THREAD

**Issue by Harrisonkamau** [NMonda/keja-app#1]
Hello @NMonda 

[This line](https://github.com/NMonda/keja-app/blob/master/client/src/App.js#L10) I'm guessing is what is returning a 404? That should be pointing to a backend endpoint. Meaning it should have a protocol such as HTTP or HTTPS. I'm not sure what port the backend server is running on. 

Second, there is no need to install `axios` on your React app. You can use `fetch` which is a [DOM API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

### Technical Implementation
Since you want to load up this [backend endpoint](https://github.com/NMonda/keja-app/blob/master/backend/app.js#L25) on your React app, then [this line](https://github.com/NMonda/keja-app/blob/master/client/src/App.js#L10) should definitely change to have the following:
```javascript
useEffect(() => {
  async function fetchData() {
    const response = await fetch('http://localhost:5500/api/listings');
    const data = await response.json();
    setListings(data);
  }

  fetchData();
}, []);

```

**Comment by NMonda** [comment]
ok thanks, done
 i will push an updated one
